import {versionAt,eventAt,comparePosition} from '/select-at.js';
import {layoutGraph,drawGraph} from '/graph.js';
import {renderNotebookMarkdown} from '/notebook-markdown.js';
const $=id=>document.getElementById(id);
let catalog=[],view=null,cursor={elapsedMs:0,order:0},positions=new Map(),selected=null,request=0,notebookId;
const fmt=ms=>`${String(Math.floor(Math.max(0,ms)/60000)).padStart(2,'0')}:${String(Math.floor(Math.max(0,ms)/1000)%60).padStart(2,'0')}`;
const put=(id,text)=>{$(id).textContent=text;};
async function get(url){const response=await fetch(url);const data=await response.json();if(!response.ok)throw new Error(data.error??'读取失败');return data;}
function showError(error){$('error').hidden=false;put('error',error.message);}
function eventTitle(event){
  const phase={started:'开始',progress:'进行中',completed:'完成',failed:'失败',interrupted:'中断',info:'记录'}[event.phase];
  if(event.kind==='command')return `命令 · ${phase}`;
  if(event.kind==='message')return `Agent 输出 · ${phase}`;
  if(event.kind==='write')return `文件更新 · ${phase}`;
  return event.title.length>100?event.title.slice(0,97)+'…':event.title;
}
function latestPosition(){return [{elapsedMs:view.encounter.elapsedMs,order:0},...view.events.map(e=>e.position),...view.graph.versions.map(v=>v.visibleFrom),...view.notebook.versions.map(v=>v.visibleFrom)].sort(comparePosition).at(-1);}
function options(select,items,value){select.replaceChildren(...items.map(([id,label])=>{const o=document.createElement('option');o.value=id;o.textContent=label;return o;}));select.value=value;select.disabled=false;}
function fillEncounters(){const items=catalog.filter(e=>e.trajectoryId===$('trajectory').value);options($('encounter'),items.map(e=>[e.id,`${e.id.split('/').at(-1).toUpperCase()} · ${e.title}`]),items[0]?.id);if(items.length)loadEncounter(items[0].id);}
async function loadEncounter(id){
  const ticket=++request;put('status','正在载入');$('error').hidden=true;
  for(const key of ['scrubber','start','end'])$(key).disabled=true;
  try {
    const next=await get('/api/encounter?id='+encodeURIComponent(id));if(ticket!==request)return;
    view=next;selected=null;notebookId=null;positions=layoutGraph(view.graph.versions);cursor=latestPosition();
    put('status',`${view.live?'运行中':'历史回放'} · ${{completed:'已完成',failed:'失败',running:'运行中',queued:'等待',interrupted:'已中断'}[view.encounter.status]}`);
    $('scrubber').max=String(Math.max(view.encounter.budgetMs,cursor.elapsedMs,1));
    put('budget','/ '+fmt(view.encounter.budgetMs));put('budget-end',fmt(Number($('scrubber').max)));put('actual-time',`实际结束 ${fmt(view.encounter.elapsedMs)}`);
    for(const key of ['scrubber','start','end'])$(key).disabled=!view.encounter.startedAt;
    $('diagnostics').hidden=!view.diagnostics.length;$('diagnostics').querySelector('pre').textContent=view.diagnostics.map(d=>d.message).join('\n\n');
    renderTrace();render(true);
  }catch(error){if(ticket===request){view=null;put('status','读取失败');showError(error);}}
}
function renderTrace(){
  $('trace').replaceChildren();put('event-count',`${view.events.length} EVENTS`);
  for(const event of view.events){
    const row=document.createElement('div');row.className='trace-event';row.dataset.eventId=event.id;
    const button=document.createElement('button');button.className='event-select';const time=document.createElement('time');time.textContent=fmt(event.position.elapsedMs);const title=document.createElement('strong');title.textContent=eventTitle(event);button.append(time,title);
    button.onclick=()=>{cursor=event.position;render(false);};row.append(button);
    if(event.detail||eventTitle(event)!==event.title){const details=document.createElement('details');details.className='event-detail';const summary=document.createElement('summary');summary.textContent='查看内容';const pre=document.createElement('pre');pre.textContent=event.detail||event.title;details.append(summary,pre);row.append(details);}
    $('trace').append(row);
  }
  if(!view.events.length){const p=document.createElement('p');p.className='empty';p.textContent='尚无运行记录。';$('trace').append(p);}
}
/** Only HTML generated by the configured Markdown parser enters this surface. */
function notebook(text){
  const host=$('notebook');host.replaceChildren();
  if(!text){const p=document.createElement('p');p.className='empty';p.textContent='此时尚未记录笔记。';host.append(p);return;}
  host.innerHTML=renderNotebookMarkdown(text);
}
function render(scroll){
  if(!view)return;
  const graph=versionAt(view.graph,cursor),note=versionAt(view.notebook,cursor),event=eventAt(view.events,cursor);
  put('cursor-time',fmt(cursor.elapsedMs));$('scrubber').value=String(cursor.elapsedMs);
  for(const row of $('trace').children){const active=row.dataset.eventId===event?.id;row.classList.toggle('active',active);const b=row.querySelector('button');if(b)b.setAttribute('aria-current',String(active));if(active&&scroll){const pane=$('trace');pane.scrollTop=row.offsetTop-pane.offsetTop-pane.clientHeight/2;}}
  put('operation',event?eventTitle(event):'尚无运行记录');
  const remark=view.remarks.filter(r=>comparePosition(r.position,cursor)<=0).sort((a,b)=>comparePosition(a.position,b.position)).at(-1);put('remark',remark?.text??'尚无留言');
  const content=graph?.content??{nodes:[],edges:[]};
  if(selected&&!content.nodes.some(n=>n.id===selected))selected=null;
  const inherited=new Set(view.graph.versions.filter(v=>v.origin==='inherited').flatMap(v=>v.content.nodes.map(n=>n.id)));
  drawGraph($('graph'),content,positions,inherited,selected,id=>{selected=id;render(false);});
  put('graph-count',`${content.nodes.length} NODES / ${content.edges.length} LINKS`);
  $('graph-empty').hidden=content.nodes.length>0;put('graph-empty',graph?'此时尚未记录节点':'此时没有可用的 graph 快照');
  const origin={inherited:'开始时的状态',end_checkpoint:'结束快照',runtime_capture:'已记录更新',trace_reconstruction:'从 trace 重建'};
  const acceptance={accepted:'已接受',draft:'草稿',rejected:'未接受'};
  put('graph-caption',`${graph?`${origin[graph.origin]} · ${acceptance[graph.acceptance]}`:'无可用快照'}${view.graph.coverage==='endpoints_only'?'　/　本次仅保存开始与结束快照；中途显示最近的已记录状态。':''}`);
  const node=content.nodes.find(n=>n.id===selected);$('node-detail').hidden=!node;if(node){put('node-label',node.label);put('node-description',node.description??'暂无描述');put('node-id',node.id);}
  if(notebookId!==note?.id){notebook(note?.content);notebookId=note?.id;}
  put('notebook-version',note?`${origin[note.origin]} · ${acceptance[note.acceptance]}`:'无可用快照');
}
$('trajectory').onchange=fillEncounters;$('encounter').onchange=()=>loadEncounter($('encounter').value);
$('scrubber').oninput=()=>{cursor={elapsedMs:Number($('scrubber').value),order:Number.MAX_SAFE_INTEGER};render(true);};
$('start').onclick=()=>{cursor={elapsedMs:0,order:0};render(true);};$('end').onclick=()=>{cursor=latestPosition();render(true);};$('close-node').onclick=()=>{selected=null;render(false);};
try{catalog=await get('/api/encounters');if(!catalog.length){put('status','暂无 encounter');put('trace','还没有可读取的本地 encounter。');}else{const trajectories=[...new Set(catalog.map(e=>e.trajectoryId))];const first=trajectories.find(id=>id.includes('/WLK'))??trajectories[0];options($('trajectory'),trajectories.map(id=>[id,id.split('/').at(-1)]),first);fillEncounters();}}catch(error){put('status','读取失败');showError(error);}
